# $Id$

- name: update
  query: UPDATE entry SET title = $title, content = $content, mdate = current_timestamp WHERE id = $id

# Local Variables:
# mode: conf-colon
# coding: iso-8859-1
# tab-width: 2
# indent-tabs-mode: nil
# End:
